### ISSUE TITLE
Consider using php-cs-fixer's yoda_style rule (or @Symfony as whole?)

### ISSUE THREAD

**Issue by sustmi** [shopsys/coding-standards#10]
Besides few exceptions, we do not use [*Yoda-style conditions*](https://en.wikipedia.org/wiki/Yoda_conditions) like:
```php
if (null === $variable) {
// ...
```
Symfony, however, has this rule in its coding standards: http://symfony.com/doc/current/contributing/code/standards.html#structure

PHP-CS-Fixer has a rule for either forcing Yoda-style conditions or non-Yoda-style conditions: https://github.com/FriendsOfPHP/PHP-CS-Fixer (search for "yoda_style").

On one hand we could enable non-Yoda-style conditions because this is the current state of the code. On the other hand, to be compatible with Symfony coding standards, it would be better to enable Yoda-style conditions and flip the sides throughout the codebase.

Note: I tried to set `'yoda_style' => false` but it did not work. You need to use the specific options like: `'yoda_style' => ['identical' => false]`.

**Comment by sustmi** [comment]
BTW: Personally, I do not like Yoda-style conditions. But, in the beginning, I did not like 4-spaces indentation too and I got used to it for the sake of consistency with PSR-2/Symfony community.

**Comment by sustmi** [comment]
Note that we probably do not use many other `@Symfony` rules. So maybe the question is not whether to use `yoda_style` but why not change the coding standards as close to `@Symfony` as possible.

But some of their rules seem just insane! Like `phpdoc_align` for example. :/

**Comment by sustmi** [comment]
I tried to enable `@Symfony` and then find all the rules that we would need to disable for the current Shopsys Framework code to pass the checks and this is the result:
```php
->setRules([
    '@PSR2' => true,
    '@Symfony' => true,

    // no! please, no
    'phpdoc_align' => false,

    // it just does not seem to me right to read this
    'concat_space' => ['spacing' => 'one'], // 'some'.'string'.$var
    'cast_spaces' => false, // $x = (int) $var;
    'yoda_style' => false, // if (false === $var)

    // not sure about these
    'blank_line_before_statement' => false,
    'class_attributes_separation' => false,
    'phpdoc_no_alias_tag' => false, // prefers @see over @link
    'increment_style' => false, // should we prefer pre-increment?

    // we should have these enabled!
    'no_blank_lines_after_class_opening' => false,
    'no_extra_consecutive_blank_lines' => false,
    'phpdoc_summary' => false,
    'phpdoc_separation' => false,
    'phpdoc_types' => false,
    'phpdoc_to_comment' => false,
    'phpdoc_inline_tag' => false,
])

**Comment by TomasVotruba** [comment]
Thanks for opening this. I'd probably go with `@Symfony` minus few rather "text styling" rules, that you've already listed.

**Comment by simara-svatopluk** [comment]
Thanks for noticing, but we will not adapt Yoda style
