### ISSUE TITLE
Upgrade PHP CS Fixer to 2.x

### ISSUE THREAD

**Issue by sustmi** [shopsys/coding-standards#3]
It looks like 1.x branch of PHP CS Fixer will not get any new features and most of the development effort is now focused on 2.x.
Also 2.1 supports passing multiple files to the command (https://github.com/FriendsOfPHP/PHP-CS-Fixer#using-php-cs-fixer-on-ci) so we can remove our hackish solution (https://github.com/shopsys/coding-standards/commit/510880e9915c25c73ea6849b820114993353bb36#diff-f9b77c41bb5671463912acc8217d4e32R72).

Here is upgrade guide: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.0.0/UPGRADE.md

Original discussion here: https://github.com/shopsys/coding-standards/commit/510880e9915c25c73ea6849b820114993353bb36#commitcomment-20856836

**Comment by PetrHeinz** [comment]
Fixed in 3.0.0
