### ISSUE TITLE
New Doctrine fixers for inspiration

### ISSUE THREAD

**Issue by TomasVotruba** [shopsys/coding-standards#4]
You might like new Doctrine fixers, from version 2.2, https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2220

**Comment by PetrHeinz** [comment]
Thank you  for the tip, Tomáš.

Automatic fixing of doctrine annotations seems useful, it can get messy at times. It may take a while to adopt though, as our priority is making SSFW easily updatable.

**Comment by TomasVotruba** [comment]
Sure, I understand that.
