### ISSUE TITLE
Make use of slevomat and object-calisthenics to move from phpmd

### ISSUE THREAD

**Issue by TomasVotruba** [shopsys/coding-standards#7]
These rules of `phpmd`:

- `ShortVariable`
- `ShortMethodName`
- `UnusedPrivateMethod`
- `ExcessivePublicCount`
- `ExcessiveClassLength`
- `ExcessiveMethodLength`

**are already implemented in these 2 packages** for PHP_CodeSniffer as Sniffs:

- https://github.com/object-calisthenics/phpcs-calisthenics-rules - you gonna love it, if you like strictness, and I can see you do :)
- https://github.com/slevomat/coding-standard

And few more useful rules, that could be added to `rulesetCS.xml`. Both packages are well maintained and up-to-date with PHP_CodeSniffer 3.x.

By using them, you could easily drop `phpmd` that never fix the code for you and move to `PHP_CodeSniffer` and `PHP CS Fixer` who do.

**Comment by sustmi** [comment]
Are there any replacements for `ExitExpression` and `Superglobals` rules too?

**Comment by TomasVotruba** [comment]
Hey,if you really needs those = it happened they reported something = I can write custom sniffs for both to this package. Personally I never used or saw them anywhere for last 5 years :)

After that, you'll be free from one package

**Comment by TomasVotruba** [comment]
@sustmi Here is demo: https://github.com/TomasVotruba/coding-standards/pull/1/files
