### ISSUE TITLE
Review contents of README.md after merging PR#6

### ISSUE THREAD

**Issue by sustmi** [shopsys/coding-standards#8]
The PR to be merged: https://github.com/TomasVotruba/coding-standards/blob/ac9212c5c5517efada4a59780f10265fb6b59514/README.md

The overall structure and texts can be improved (namely):
- a paragraph with colon should not be followed by a H3: https://github.com/TomasVotruba/coding-standards/blame/ac9212c5c5517efada4a59780f10265fb6b59514/README.md#L12
- installation guide should be first, then usage and then documentation of custom coding standards

**Comment by sustmi** [comment]
The proposed README is here: https://gist.github.com/sustmi/7059ac02a91ddd3cffa24398f15c680a

**Comment by vitek-rostislav** [comment]
Hi @sustmi, 

thank you for noticing, the README.md was improved according to your notes in c741b2c .
